defaults: &defaults
  adapter: postgresql
  database: renta_development
  pool: 5
  encoding: utf8
  host: localhost

development:
  <<: *defaults

test: &test
  <<: *defaults
  database: renta_test

staging:
  <<: *defaults

production:
  <<: *defaults

cucumber:
  <<: *test